# This is a docker compose configuration file for development ONLY.
# A new one will need to be written for production, without bind mounts, and other changes.

version: '2.0'
services:
  flask:
    build: .
    image: mathlm:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app # Mount the current directory in the container, so changes made in the container are reflected on the host.
